### PR TITLE
Fix failure on 204 in the node environment

### PR DESCRIPTION
**Pull request by markwoon**
Fix failure on 204 in the node environment

### CODE REVIEW

**Comment by tnguyen14** [comment]
Hi,

Could you explain the issue a bit further? And instead of `""`, could you use `''`, to be more consistent with the rest of the code?

Last but not least, this is probably a bug with upstream AmpersandJS/ampersand-sync as well. Should a PR be opened there?

**Comment by aclimatt** [comment]
Hi,

Sorry about the double quotes, fixed to single quotes!

So, the problem we were experiencing is that we have an endpoint that returns a `204`. With `request` in the browser, the body is `null`, however in Node (server-side rendering) the body is an empty string. This causes the JSON parse to fail and the promise to reject only on server-side rendering.

Now, this could potentially be solved by submitting a PR to `request` to fix this behavior, but for such a big library it's hard to say if this behavior is intended or not, and that change could have sweeping consequences. So it's probably unlikely that we could change that behavior.

We could also submit this same PR to `AmpersandJS/ampersand-sync` instead since the code originally comes from there; are you still tracking from upstream? Just want to make sure we can still use this library with the fix.

Let me know your preference. Thanks!

**Comment by tnguyen14** [comment]
Hi, please submit a PR to `AmpersandJS/ampersand-sync`, and once that's merged, I will update this fork from upstream.

I do try to stay updated with `ampersand-sync`, and not let it diverge too much.

**Comment by aclimatt** [comment]
Hi,

This has been merged upstream and published as `v5.0.1`. Thanks!

Edit: @markwoon, we can probably close this PR then.

**Comment by tnguyen14** [comment]
Thanks for staying on this. Upstream fixes have been released in `v5.0.0` of this package.

**Pull request closed without merging**
