### PR TITLE
throw error for response codes >= 400

### PR DESCRIPTION
**Pull request by hngu**
The ampersand-sync project does a check on the response code detailed here:

https://github.com/AmpersandJS/ampersand-sync/blob/master/core.js#L121

I need this so that my client side code can properly handle these types of responses.

### CODE REVIEW

**Comment by tnguyen14** [comment]
@hngu thanks. is this from upstream? if so, I could just update this with upstream.

**Comment by hngu** [comment]
@tnguyen14 I am not sure but this is a branch off of master which I pulled last weekend.

**Comment by tnguyen14** [comment]
@hngu I've just updated the master branch to include the latest updates from upstream AmpersandJS/ampersand-sync. Please check it out, it should do what you want it to.

**Comment by hngu** [comment]
There seems to be a problem with 3.0.0. When I test an ajax request that returns 500 error code, the callback I attach to the `.done()` does not get called. The failure callback in `.then()` works though.

**Comment by tnguyen14** [comment]
@hngu I don't think `.done()` is part of the Promise A+ spec, it's only a jQuery thing. So I'd say if you're using promises, go with `.then()`. 

In this implementation I also purposefully left out `always` callback. But maybe I could consider putting it in somehow.

**Comment by hngu** [comment]
Ok I see. I will close this PR and open a feature request for now. Thank you!

**Comment by hngu** [comment]
@tnguyen14 I cannot create an issue. Can you enable it?

**Comment by tnguyen14** [comment]
@hngu I didn't even realized that. should be open now.

**Pull request closed without merging**
